Admin.create(email: 'admin@sp.com', password: 'dddddd', password_confirmation: 'dddddd')
company1 = Company.create(name: '架空株式会社')
  manager1 = Manager.create(manager_name: '鈴木一郎', email: 'i-suzuki@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
  manager2 = Manager.create(manager_name: '岡田太郎', email: 't-okada@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
  user1 = User.create(user_name: '鈴木一郎', email: 'i-suzuki@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
    Card.create(number: 1, user: user1)
  user2 = User.create(user_name: '山田二郎', email: 'j-yamada@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
    Card.create(number: 0, user: user2)
  user3 = User.create(user_name: '沢田三郎', email: 's-sawada@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
    Card.create(number: 2, user: user3)
  user4 = User.create(user_name: '佐藤四郎', email: 's-sato@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
    Card.create(number: 0, user: user4)
  user5 = User.create(user_name: '与田五郎', email: 'g-yoda@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
    Card.create(number: 1, user: user5)
  user6 = User.create(user_name: '内田六郎', email: 'g-uchida@sp.com', password: 'dddd', password_confirmation: 'dddd', company: company1)
    Card.create(number: 1, user: user6)

  car1 = Car.create(car_name: 'バネット', region: '大宮147', number: 'ま5389', purchase_day: '2018-11-30', borrower: user1.user_name, parking: '町田支社', tank: 50, oil_frequency: 5000, initial_mileage: 18, initial_odometer: 15, state: '空車', company: company1)
    car1.reservations.create(user_id: user2.id, reservation_day: '2020-7-3')
    car1.reservations.create(user_id: user3.id, reservation_day: '2020-7-9')
    car1.reservations.create(user_id: user2.id, reservation_day: '2020-7-15')
    car1.reservations.create(user_id: user4.id, reservation_day: '2020-7-24')
    car1.reservations.create(user_id: user3.id, reservation_day: '2020-8-6')
    car1.reservations.create(user_id: user3.id, reservation_day: '2020-8-12')
    car1.reservations.create(user_id: user4.id, reservation_day: '2020-8-19')
    car1.reservations.create(user_id: user4.id, reservation_day: '2020-8-30')
    car1.uses.create(user_id: user1.id, use_day: '2020-1-22', odometer: 30, distance: 15, destination: '川口市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-2-3', odometer: 152, distance: 122, destination: '土田工業', refueling_amount: 25.45, wash: '有', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user3.id, use_day: '2020-2-14', odometer: 376, distance: 224, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-2-16', odometer: 500, distance: 124, destination: '三田製薬', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user2.id, use_day: '2020-3-19', odometer: 748, distance: 248, destination: '熱海市役所', refueling_amount: 14.09, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-4-4', odometer: 902, distance: 154, destination: '土田工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user4.id, use_day: '2020-4-19', odometer: 993, distance: 91, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
      car1.inspections.create(start_day: '2020-4-19', end_day: '2020-4-20', fee: 120000, limit: '2022-4-19', inspection_memo: 'マフラー交換')
    car1.uses.create(user_id: user4.id, use_day: '2020-4-20', odometer: 1084, distance: 91, destination: 'オートバックス町田店', refueling_amount: 19.20, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-5-23', odometer: 1354, distance: 270, destination: '熱海市役所', refueling_amount: 17.08, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user2.id, use_day: '2020-6-1', odometer: 1502, distance: 148, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-4', odometer: 1750, distance: 248, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-5', odometer: 2140, distance: 390, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-7', odometer: 3050, distance: 910, destination: '熱海市役所', refueling_amount: 39.92, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-14', odometer: 3567, distance: 517, destination: '三室重工業', refueling_amount: 45.64, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-16', odometer: 4030, distance: 463, destination: '富士製鉄', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user2.id, use_day: '2020-6-17', odometer: 4500, distance: 470, destination: '富士製鉄', refueling_amount: 45.66, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-18', odometer: 4677, distance: 177, destination: '土田工業', refueling_amount: 20.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-19', odometer: 4798, distance: 121, destination: '三田製紙', refueling_amount: 48.45, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user5.id, use_day: '2020-6-21', odometer: 5345, distance: 547, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user4.id, use_day: '2020-6-23', odometer: 5517, distance: 172, destination: '熱海市役所', refueling_amount: 45.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-6-25', odometer: 5527, distance: 10, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-7-2', odometer: 5548, distance: 21, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-7-3', odometer: 5650, distance: 102, destination: '三田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user4.id, use_day: '2020-7-5', odometer: 5749, distance: 99, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-7-6', odometer: 5970, distance: 221, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-7-8', odometer: 6051, distance: 81, destination: '土田工業', refueling_amount: 28.56, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user2.id, use_day: '2020-7-9', odometer: 6456, distance: 405, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-7-11', odometer: 6809, distance: 353, destination: '富士製鉄', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.uses.create(user_id: user1.id, use_day: '2020-7-12', odometer: 6892, distance: 83, destination: '土田工業', refueling_amount: 55.89, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car1.memos.create(memo_day: '2020-4-1', content: 'タイヤ交換')
    car1.memos.create(memo_day: '2020-5-1', content: 'ワイパー交換')
    car1.memos.create(memo_day: '2020-5-13', content: 'ナビ設置')
    car1.memos.create(memo_day: '2020-7-5', content: 'ホイル交換')
    Car.find(1).update(mileage: (car1.uses.where.not(refueling_amount: 0).order(:id).last.odometer - car1.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/car1.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)

  car2 = Car.create(car_name: 'マーチ', region: '墨田147', number: 'む2266', purchase_day: '2016-3-6', borrower: user2.user_name, parking: '本社', tank: 50, oil_frequency: 5000, initial_mileage: 20, initial_odometer: 200, state: '空車', company: company1)
    car2.reservations.create(user_id: user1.id, reservation_day: '2020-7-4')
    car2.reservations.create(user_id: user1.id, reservation_day: '2020-7-10')
    car2.reservations.create(user_id: user1.id, reservation_day: '2020-7-16')
    car2.reservations.create(user_id: user4.id, reservation_day: '2020-7-25')
    car2.reservations.create(user_id: user3.id, reservation_day: '2020-8-7')
    car2.reservations.create(user_id: user3.id, reservation_day: '2020-8-13')
    car2.reservations.create(user_id: user4.id, reservation_day: '2020-8-20')
    car2.reservations.create(user_id: user4.id, reservation_day: '2020-9-1')
    car2.inspections.create(start_day: '2018-7-19', end_day: '2018-7-21', fee: 120000, limit: '2020-7-19', inspection_memo: 'ヘッドライト交換')
    car2.uses.create(user_id: user2.id, use_day: '2020-1-2', odometer: 30, distance: 15, destination: '港区役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-1-3', odometer: 152, distance: 122, destination: '土田工業', refueling_amount: 25.45, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user3.id, use_day: '2020-1-14', odometer: 376, distance: 224, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-1-16', odometer: 500, distance: 124, destination: '三田製薬', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-2-19', odometer: 748, distance: 248, destination: '熱海市役所', refueling_amount: 14.09, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user1.id, use_day: '2020-3-4', odometer: 902, distance: 154, destination: '土田工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user4.id, use_day: '2020-3-19', odometer: 993, distance: 91, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user4.id, use_day: '2020-3-20', odometer: 1084, distance: 91, destination: 'オートバックス町田店', refueling_amount: 19.20, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-4-23', odometer: 1354, distance: 270, destination: '熱海市役所', refueling_amount: 15.08, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-5-1', odometer: 1502, distance: 148, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-5-4', odometer: 1750, distance: 248, destination: '熱海市役所', refueling_amount: 45.09, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user1.id, use_day: '2020-5-5', odometer: 2140, distance: 390, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-5-7', odometer: 3050, distance: 910, destination: '熱海市役所', refueling_amount: 39.92, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-6-14', odometer: 3567, distance: 517, destination: '三室重工業', refueling_amount: 45.64, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-6-16', odometer: 4030, distance: 463, destination: '富士製鉄', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-6-17', odometer: 4500, distance: 470, destination: '富士製鉄', refueling_amount: 45.66, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user3.id, use_day: '2020-6-18', odometer: 4677, distance: 177, destination: '土田工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user4.id, use_day: '2020-6-19', odometer: 4798, distance: 121, destination: '三田製紙', refueling_amount: 40.45, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user5.id, use_day: '2020-6-21', odometer: 5345, distance: 547, destination: '三室重工業', refueling_amount: 0.00, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user4.id, use_day: '2020-6-23', odometer: 5677, distance: 332, destination: '熱海市役所', refueling_amount: 45.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-6-25', odometer: 5887, distance: 210, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
    car2.uses.create(user_id: user2.id, use_day: '2020-7-6', odometer: 6008, distance: 121, destination: '三田製紙', refueling_amount: 35.45, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-7-8', odometer: 6555, distance: 547, destination: '三室重工業', refueling_amount: 0.00, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user4.id, use_day: '2020-7-10', odometer: 6887, distance: 332, destination: '熱海市役所', refueling_amount: 45.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car2.uses.create(user_id: user2.id, use_day: '2020-7-11', odometer: 7097, distance: 210, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
    car2.memos.create(memo_day: '2020-5-21', content: 'タイヤ交換')
    car2.memos.create(memo_day: '2020-4-1', content: 'ナビ設置')
    car2.memos.create(memo_day: '2020-4-13', content: 'ワイパー交換')
    Car.find(2).update(mileage: (car2.uses.where.not(refueling_amount: 0).order(:id).last.odometer - car2.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/car2.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)
    Car.find(2).update(state: '車検中')

  car3 = Car.create(car_name: 'レクサス', region: '品川346', number: 'は8724', purchase_day: '2020-3-6', borrower: user3.user_name, parking: '本社', tank: 80, oil_frequency: 5000, initial_mileage: 20, initial_odometer: 15, state: '空車', company: company1)
    car3.reservations.create(user_id: user1.id, reservation_day: '2020-7-5')
    car3.reservations.create(user_id: user1.id, reservation_day: '2020-7-11')
    car3.reservations.create(user_id: user1.id, reservation_day: '2020-7-17')
    car3.reservations.create(user_id: user4.id, reservation_day: '2020-7-26')
    car3.reservations.create(user_id: user2.id, reservation_day: '2020-8-8')
    car3.reservations.create(user_id: user2.id, reservation_day: '2020-8-14')
    car3.reservations.create(user_id: user4.id, reservation_day: '2020-8-21')
    car3.reservations.create(user_id: user4.id, reservation_day: '2020-9-2')
    car3.uses.create(user_id: user3.id, use_day: '2020-4-2', odometer: 30, distance: 15, destination: '品川区役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-4-3', odometer: 152, distance: 122, destination: '土田工業', refueling_amount: 25.45, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-4-14', odometer: 376, distance: 224, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-4-16', odometer: 500, distance: 124, destination: '三田製薬', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user2.id, use_day: '2020-4-19', odometer: 748, distance: 248, destination: 'オートバックス町田店', refueling_amount: 14.09, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user1.id, use_day: '2020-5-4', odometer: 902, distance: 154, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-5-19', odometer: 993, distance: 91, destination: '土田工業', refueling_amount: 0.00, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user4.id, use_day: '2020-5-20', odometer: 1084, distance: 91, destination: '富田金属', refueling_amount: 19.20, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-5-23', odometer: 1354, distance: 270, destination: '熱海市役所', refueling_amount: 15.08, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-1', odometer: 1502, distance: 148, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-4', odometer: 1750, distance: 248, destination: '熱海市役所', refueling_amount: 45.09, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-5', odometer: 2140, distance: 390, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user2.id, use_day: '2020-6-7', odometer: 3050, distance: 910, destination: '熱海市役所', refueling_amount: 39.92, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-14', odometer: 3567, distance: 517, destination: '三室重工業', refueling_amount: 45.64, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-16', odometer: 4030, distance: 463, destination: '富士製鉄', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-17', odometer: 4500, distance: 470, destination: '富士製鉄', refueling_amount: 45.66, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-18', odometer: 4677, distance: 177, destination: '土田工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user4.id, use_day: '2020-6-19', odometer: 4798, distance: 121, destination: '三田製紙', refueling_amount: 40.45, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-21', odometer: 5345, distance: 547, destination: '三室重工業', refueling_amount: 29.01, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-23', odometer: 5677, distance: 332, destination: '熱海市役所', refueling_amount: 18.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-6-25', odometer: 5887, distance: 210, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user4.id, use_day: '2020-7-1', odometer: 6009, distance: 122, destination: '三田製紙', refueling_amount: 15.45, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-7-2', odometer: 6080, distance:71, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-7-3', odometer: 6308, distance: 228, destination: '熱海市役所', refueling_amount: 18.07, wash: '無', oil_change: '無', self_inspection: '有', inspection_st: '無')
    car3.uses.create(user_id: user3.id, use_day: '2020-7-5', odometer: 6400, distance:92, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car3.memos.create(memo_day: '2020-3-31', content: 'ナビ設置')
    car3.memos.create(memo_day: '2020-4-13', content: 'ワイパー交換')
    car3.memos.create(memo_day: '2020-4-21', content: 'タイヤ交換')
    Car.find(3).update(mileage: (car3.uses.where.not(refueling_amount: 0).order(:id).last.odometer - car3.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/car3.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)
    Car.find(3).update(state: "#{user3.user_name}が乗車中")

    car4 = Car.create(car_name: 'ヤリス', region: '品川233', number: 'は6554', purchase_day: '2020-7-2', borrower: user4.user_name, parking: '本社', tank: 60, oil_frequency: 5000, initial_mileage: 20, initial_odometer: 5345, state: '空車', company: company1)
      car4.reservations.create(user_id: user5.id, reservation_day: '2020-7-6')
      car4.reservations.create(user_id: user2.id, reservation_day: '2020-7-12')
      car4.reservations.create(user_id: user2.id, reservation_day: '2020-7-18')
      car4.reservations.create(user_id: user5.id, reservation_day: '2020-7-27')
      car4.reservations.create(user_id: user5.id, reservation_day: '2020-8-9')
      car4.reservations.create(user_id: user5.id, reservation_day: '2020-8-15')
      car4.reservations.create(user_id: user5.id, reservation_day: '2020-8-22')
      car4.reservations.create(user_id: user5.id, reservation_day: '2020-9-3')
      car4.uses.create(user_id: user4.id, use_day: '2020-7-3', odometer: 5350, distance: 5, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
      car4.uses.create(user_id: user4.id, use_day: '2020-7-5', odometer: 5402, distance: 52, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
        car4.update(state: "#{user4.user_name}が乗車中")

  car5 = Car.create(car_name: '高所作業車', region: '品川744', number: 'か0896', purchase_day: '2019-10-10', borrower: '共用', parking: '本社', tank: 90, oil_frequency: 10000, initial_mileage: 7, initial_odometer: 10000, state: '空車', company: company1)
    car5.reservations.create(user_id: user3.id, reservation_day: '2020-7-7')
    car5.reservations.create(user_id: user2.id, reservation_day: '2020-7-19')
    car5.reservations.create(user_id: user2.id, reservation_day: '2020-7-28')
    car5.reservations.create(user_id: user3.id, reservation_day: '2020-8-16')
    car5.reservations.create(user_id: user2.id, reservation_day: '2020-8-23')
    car5.reservations.create(user_id: user4.id, reservation_day: '2020-9-10')
    car5.uses.create(user_id: user1.id, use_day: '2020-1-9', odometer: 10030, distance: 30, destination: '大橋架替現場', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-1-18', odometer: 10152, distance: 122, destination: '巴橋架替現場', refueling_amount: 25.45, wash: '有', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user3.id, use_day: '2020-2-14', odometer: 10376, distance: 224, destination: '吾妻橋架替現場', refueling_amount: 50.45, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-2-16', odometer: 10500, distance: 124, destination: '巴橋架替現場', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user2.id, use_day: '2020-3-19', odometer: 10748, distance: 248, destination: '吾妻橋架替現場', refueling_amount: 44.09, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-4-4', odometer: 10902, distance: 154, destination: '岩間陸橋改修現場', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user4.id, use_day: '2020-4-29', odometer: 10993, distance: 91, destination: 'オートバックス町田店', refueling_amount: 35.03, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
      car5.inspections.create(start_day: '2020-4-29', end_day: '2020-5-2', fee: 120000, limit: '2022-4-29', inspection_memo: 'マフラー交換')
    car5.uses.create(user_id: user4.id, use_day: '2020-5-21', odometer: 11084, distance: 91, destination: 'オートバックス町田店', refueling_amount: 25.20, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-5-23', odometer: 11354, distance: 270, destination: '吾妻橋架替現場', refueling_amount: 25.08, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user2.id, use_day: '2020-6-1', odometer: 11502, distance: 148, destination: '巴橋架替現場', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-4', odometer: 11750, distance: 248, destination: '千間川橋梁改修', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-5', odometer: 12140, distance: 390, destination: '千間川橋梁改修', refueling_amount: 0.00, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-7', odometer: 13050, distance: 910, destination: '馬淵橋梁改修', refueling_amount: 69.92, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-14', odometer: 13567, distance: 517, destination: '千間川橋梁改修', refueling_amount: 68.64, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-16', odometer: 14030, distance: 463, destination: '千間川橋梁改修', refueling_amount: 60.06, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user2.id, use_day: '2020-6-17', odometer: 14500, distance: 470, destination: '千間川橋梁改修', refueling_amount: 69.66, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-18', odometer: 14677, distance: 177, destination: '吾妻橋架替現場', refueling_amount: 60.04, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-6-19', odometer: 14798, distance: 121, destination: '吾妻橋架替現場', refueling_amount: 68.45, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user5.id, use_day: '2020-6-21', odometer: 15345, distance: 547, destination: '馬淵橋梁改修', refueling_amount: 60.78, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user4.id, use_day: '2020-6-23', odometer: 15677, distance: 332, destination: '吾妻橋架替現場', refueling_amount: 62.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-7-5', odometer: 15887, distance: 210, destination: '馬淵橋梁改修', refueling_amount: 33.56, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user4.id, use_day: '2020-7-8', odometer: 16219, distance: 332, destination: '吾妻橋架替現場', refueling_amount: 62.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.uses.create(user_id: user1.id, use_day: '2020-7-10', odometer: 16129, distance: 210, destination: '馬淵橋梁改修', refueling_amount: 26.56, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car5.memos.create(memo_day: '2020-4-1', content: 'マフラー交換')
    car5.memos.create(memo_day: '2020-5-1', content: 'ナビ設置')
    car5.memos.create(memo_day: '2020-5-13', content: 'シャフト改修')
    car5.memos.create(memo_day: '2020-7-8', content: 'ETC設置')
    Car.find(5).update(mileage: (car5.uses.where.not(refueling_amount: 0).order(:id).last.odometer - car5.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/car5.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)

  car6 = Car.create(car_name: 'アクア', region: '品川645', number: 'き8743', purchase_day: '2019-12-10', borrower: user6.user_name, parking: '本社', tank: 36, oil_frequency: 5000, initial_mileage: 23, initial_odometer: 15, state: '空車', company: company1)
    car6.reservations.create(user_id: user4.id, reservation_day: '2020-7-8')
    car6.reservations.create(user_id: user2.id, reservation_day: '2020-7-20')
    car6.reservations.create(user_id: user2.id, reservation_day: '2020-7-29')
    car6.reservations.create(user_id: user3.id, reservation_day: '2020-8-17')
    car6.reservations.create(user_id: user2.id, reservation_day: '2020-8-24')
    car6.reservations.create(user_id: user4.id, reservation_day: '2020-9-11')
    car6.uses.create(user_id: user1.id, use_day: '2020-1-22', odometer: 30, distance: 15, destination: '川口市役所', refueling_amount: 0.00, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-1-23', odometer: 152, distance: 122, destination: '土田工業', refueling_amount: 6.04, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user3.id, use_day: '2020-2-14', odometer: 376, distance: 224, destination: '熱海市役所', refueling_amount: 18.22, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-2-16', odometer: 500, distance: 124, destination: '三田製薬', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '有', inspection_st: '無')
    car6.uses.create(user_id: user2.id, use_day: '2020-3-19', odometer: 748, distance: 248, destination: '熱海市役所', refueling_amount: 13.09, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-4-4', odometer: 902, distance: 154, destination: '土田工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user4.id, use_day: '2020-4-19', odometer: 993, distance: 91, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
      car6.inspections.create(start_day: '2020-4-19', end_day: '2020-4-20', fee: 120000, limit: '2022-4-19', inspection_memo: 'マフラー交換')
    car6.uses.create(user_id: user4.id, use_day: '2020-4-20', odometer: 1084, distance: 91, destination: 'オートバックス町田店', refueling_amount: 15.20, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-5-23', odometer: 1354, distance: 270, destination: '熱海市役所', refueling_amount: 13.02, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user2.id, use_day: '2020-6-1', odometer: 1502, distance: 148, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-4', odometer: 1750, distance: 248, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-5', odometer: 2140, distance: 390, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-7', odometer: 3050, distance: 910, destination: '熱海市役所', refueling_amount: 35.92, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-14', odometer: 3567, distance: 517, destination: '三室重工業', refueling_amount: 15.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-16', odometer: 4030, distance: 463, destination: '富士製鉄', refueling_amount: 30.39, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user2.id, use_day: '2020-6-17', odometer: 4500, distance: 470, destination: '富士製鉄', refueling_amount: 35.66, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-18', odometer: 4677, distance: 177, destination: '土田工業', refueling_amount: 25.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-19', odometer: 4798, distance: 121, destination: '三田製紙', refueling_amount: 30.45, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user5.id, use_day: '2020-6-21', odometer: 5345, distance: 547, destination: '三室重工業', refueling_amount: 24.34, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user4.id, use_day: '2020-6-23', odometer: 5677, distance: 332, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-6-25', odometer: 5887, distance: 210, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-7-9', odometer: 5998, distance: 111, destination: '三田製紙', refueling_amount: 30.45, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user5.id, use_day: '2020-7-10', odometer: 6545, distance: 547, destination: '三室重工業', refueling_amount: 24.34, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.uses.create(user_id: user4.id, use_day: '2020-7-11', odometer: 6877, distance: 332, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '有', inspection_st: '無')
    car6.uses.create(user_id: user1.id, use_day: '2020-7-12', odometer: 7087, distance: 210, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car6.memos.create(memo_day: '2020-4-1', content: 'タイヤ交換')
    car6.memos.create(memo_day: '2020-5-1', content: 'ワイパー交換')
    car6.memos.create(memo_day: '2020-5-13', content: 'ナビ設置')
    Car.find(6).update(mileage: (car6.uses.where.not(refueling_amount: 0).order(:id).last.odometer - car6.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/car6.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)

  car7 = Car.create(car_name: 'キャラバン', region: '越谷156', number: 'み5439', purchase_day: '2016-11-30', borrower: user4.user_name, parking: '越谷支社', tank: 70, oil_frequency: 5000, initial_mileage: 12, initial_odometer: 10, state: '空車', company: company1)
    car7.reservations.create(user_id: user2.id, reservation_day: '2020-7-1')
    car7.reservations.create(user_id: user2.id, reservation_day: '2020-7-2')
    car7.reservations.create(user_id: user4.id, reservation_day: '2020-7-30')
    car7.reservations.create(user_id: user3.id, reservation_day: '2020-8-1')
    car7.reservations.create(user_id: user4.id, reservation_day: '2020-9-12')
    car7.uses.create(user_id: user4.id, use_day: '2020-1-22', odometer: 30, distance: 20, destination: '太田区役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-1-23', odometer: 152, distance: 122, destination: '土田工業', refueling_amount: 12.45, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user3.id, use_day: '2020-2-14', odometer: 376, distance: 224, destination: '熱海市役所', refueling_amount: 30.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user1.id, use_day: '2020-2-16', odometer: 500, distance: 124, destination: '三田製薬', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user2.id, use_day: '2020-3-19', odometer: 748, distance: 248, destination: '熱海市役所', refueling_amount: 28.09, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-4-4', odometer: 902, distance: 154, destination: '土田工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-4-17', odometer: 993, distance: 91, destination: 'オートバックス町田店', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '有')
      car7.inspections.create(start_day: '2020-4-17', end_day: '2020-4-20', fee: 120000, limit: '2022-4-17', inspection_memo: 'マフラー交換')
    car7.uses.create(user_id: user4.id, use_day: '2020-4-20', odometer: 1084, distance: 91, destination: 'オートバックス町田店', refueling_amount: 30.20, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-5-23', odometer: 1354, distance: 270, destination: '熱海市役所', refueling_amount: 30.08, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user2.id, use_day: '2020-6-1', odometer: 1502, distance: 148, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-4', odometer: 1750, distance: 248, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-5', odometer: 2140, distance: 390, destination: '三室重工業', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-7', odometer: 3050, distance: 910, destination: '熱海市役所', refueling_amount: 69.92, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-14', odometer: 3567, distance: 517, destination: '三室重工業', refueling_amount: 55.64, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-16', odometer: 4030, distance: 463, destination: '富士製鉄', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user2.id, use_day: '2020-6-17', odometer: 4500, distance: 470, destination: '富士製鉄', refueling_amount: 55.66, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user1.id, use_day: '2020-6-18', odometer: 4677, distance: 177, destination: '土田工業', refueling_amount: 65.68, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-19', odometer: 4798, distance: 121, destination: '三田製紙', refueling_amount: 60.45, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user5.id, use_day: '2020-6-21', odometer: 5345, distance: 547, destination: '三室重工業', refueling_amount: 52.01, wash: '無', oil_change: '有', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-23', odometer: 5677, distance: 332, destination: '熱海市役所', refueling_amount: 33.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-6-25', odometer: 5887, distance: 210, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-1', odometer: 6035, distance: 148, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-2', odometer: 6283, distance: 248, destination: '熱海市役所', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-3', odometer: 6673, distance: 390, destination: '三室重工業', refueling_amount: 0.00, wash: '有', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-4', odometer: 7583, distance: 910, destination: '熱海市役所', refueling_amount: 69.92, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-5', odometer: 8100, distance: 517, destination: '三室重工業', refueling_amount: 65.64, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-6', odometer: 8563, distance: 463, destination: '富士製鉄', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-7', odometer: 9033, distance: 470, destination: '富士製鉄', refueling_amount: 65.66, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-8', odometer: 9210, distance: 177, destination: '土田工業', refueling_amount: 55.68, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user1.id, use_day: '2020-7-9', odometer: 9331, distance: 121, destination: '三田製紙', refueling_amount: 60.45, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user5.id, use_day: '2020-7-10', odometer: 9878, distance: 547, destination: '三室重工業', refueling_amount: 52.01, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-11', odometer: 10210, distance: 332, destination: '熱海市役所', refueling_amount: 33.07, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.uses.create(user_id: user4.id, use_day: '2020-7-13', odometer: 10420, distance: 210, destination: '岡田製紙', refueling_amount: 0.00, wash: '無', oil_change: '無', self_inspection: '無', inspection_st: '無')
    car7.memos.create(memo_day: '2020-2-1', content: 'ライト交換')
    car7.memos.create(memo_day: '2020-2-11', content: 'ワイパー交換')
    car7.memos.create(memo_day: '2020-7-11', content: 'ETC設置')
    Car.find(7).update(mileage: (car7.uses.where.not(refueling_amount: 0).order(:id).last.odometer - car7.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/car7.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)


    